
#!/usr/bin/env python
## Controller Config
# STIFFNESS_ROT_HIGH = 30
STIFFNESS_ROT_LOW =  0
# STIFFNESS_LIN_HIGH = 150
STIFFNESS_LIN_LOW = 0
DAMPING_ROT_HIGH = 9
DAMPING_ROT_LOW = 0
DAMPING_LIN_HIGH = 60
DAMPING_LIN_LOW = 0
INTEGRAL_ROT_HIGH = 3
# INTEGRAL_ROT_HIGH = 20
INTEGRAL_ROT_LOW = 0
INTEGRAL_LIN_HIGH = 60
INTEGRAL_LIN_LOW = 0
MAX_INTEGRAL_LIN_LOW = 0
MAX_INTEGRAL_LIN_HIGH = 1
MAX_INTEGRAL_ROT_LOW = 0
MAX_INTEGRAL_ROT_HIGH = 1
## Particle Filter Config
RESAMPLE_PROPORTION_HIGH = 0.042 # not used
RESAMPLE_PROPORTION_LOW = 0.0
NOISE_XY_HIGH = 0.004# 0.03 works well
NOISE_XY_LOW = 0.00001 # 0.005 works well
NOISE_THETA_HIGH = 0.0085
NOISE_THETA_LOW = 0.00002

